<?xml version="1.0" encoding="utf-8"?><Database Name="Hotel" Class="HotelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;D:\01. Programming\00. Курсовые проекты\01. Курсовой проект .NET Framework\HotelApplication\HotelApplicationWPF\App_Data\Hotel.mdf&quot;;Integrated Security=True" SettingsObjectName="HotelClassLibrary.Properties.Settings" SettingsPropertyName="HotelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="City_HistoryRegistrationHotel" Member="HistoryRegistrationHotels" ThisKey="Id" OtherKey="IdCity" Type="HistoryRegistrationHotel" />
    </Type>
  </Table>
  <Table Name="dbo.CleaningSchedule" Member="CleaningSchedules">
    <Type Name="CleaningSchedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdDayOfWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEmployee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFloor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_CleaningSchedule" Member="Employee" ThisKey="IdEmployee" OtherKey="Id" Type="Employee" IsForeignKey="true" />
      <Association Name="Floor_CleaningSchedule" Member="Floor" ThisKey="IdFloor" OtherKey="Id" Type="Floor" IsForeignKey="true" />
      <Association Name="DaysOfWeek_CleaningSchedule" Member="DaysOfWeek" ThisKey="IdDayOfWeek" OtherKey="Id" Type="DaysOfWeek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPerson" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Passport" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Client_HistoryRegistrationHotel" Member="HistoryRegistrationHotels" ThisKey="Id" OtherKey="IdClient" Type="HistoryRegistrationHotel" />
      <Association Name="Person_Client" Member="Person" ThisKey="IdPerson" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPerson" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkState" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Employee_CleaningSchedule" Member="CleaningSchedules" ThisKey="Id" OtherKey="IdEmployee" Type="CleaningSchedule" />
      <Association Name="Employee_CleaningHistory" Member="CleaningHistories" ThisKey="Id" OtherKey="IdEmployee" Type="CleaningHistory" />
      <Association Name="Person_Employee" Member="Person" ThisKey="IdPerson" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Floors" Member="Floors">
    <Type Name="Floor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Floor_CleaningSchedule" Member="CleaningSchedules" ThisKey="Id" OtherKey="IdFloor" Type="CleaningSchedule" />
      <Association Name="Floor_HotelRoom" Member="HotelRooms" ThisKey="Id" OtherKey="IdFloor" Type="HotelRoom" />
      <Association Name="Floor_CleaningHistory" Member="CleaningHistories" ThisKey="Id" OtherKey="IdFloor" Type="CleaningHistory" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryRegistrationHotel" Member="HistoryRegistrationHotels">
    <Type Name="HistoryRegistrationHotel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdClient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdHotelRoom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdCity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="City_HistoryRegistrationHotel" Member="City" ThisKey="IdCity" OtherKey="Id" Type="City" IsForeignKey="true" />
      <Association Name="Client_HistoryRegistrationHotel" Member="Client" ThisKey="IdClient" OtherKey="Id" Type="Client" IsForeignKey="true" />
      <Association Name="HotelRoom_HistoryRegistrationHotel" Member="HotelRoom" ThisKey="IdHotelRoom" OtherKey="Id" Type="HotelRoom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HotelRooms" Member="HotelRooms">
    <Type Name="HotelRoom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdTypeHotelRoom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFloor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="HotelRoom_HistoryRegistrationHotel" Member="HistoryRegistrationHotels" ThisKey="Id" OtherKey="IdHotelRoom" Type="HistoryRegistrationHotel" />
      <Association Name="Floor_HotelRoom" Member="Floor" ThisKey="IdFloor" OtherKey="Id" Type="Floor" IsForeignKey="true" />
      <Association Name="TypesHotelRoom_HotelRoom" Member="TypesHotelRoom" ThisKey="IdTypeHotelRoom" OtherKey="Id" Type="TypesHotelRoom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persons" Member="Persons">
    <Type Name="Person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="Person_Client" Member="Clients" ThisKey="Id" OtherKey="IdPerson" Type="Client" />
      <Association Name="Person_Employee" Member="Employees" ThisKey="Id" OtherKey="IdPerson" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.TypesHotelRoom" Member="TypesHotelRooms">
    <Type Name="TypesHotelRoom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CountRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TypesHotelRoom_HotelRoom" Member="HotelRooms" ThisKey="Id" OtherKey="IdTypeHotelRoom" Type="HotelRoom" />
    </Type>
  </Table>
  <Table Name="dbo.DaysOfWeek" Member="DaysOfWeeks">
    <Type Name="DaysOfWeek">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DaysOfWeek_CleaningSchedule" Member="CleaningSchedules" ThisKey="Id" OtherKey="IdDayOfWeek" Type="CleaningSchedule" />
    </Type>
  </Table>
  <Table Name="dbo.CleaningHistory" Member="CleaningHistories">
    <Type Name="CleaningHistory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFloor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCleaning" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdEmployee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_CleaningHistory" Member="Employee" ThisKey="IdEmployee" OtherKey="Id" Type="Employee" IsForeignKey="true" />
      <Association Name="Floor_CleaningHistory" Member="Floor" ThisKey="IdFloor" OtherKey="Id" Type="Floor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CitiesView" Member="CitiesViews">
    <Type Name="CitiesView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CleaningHistoryView" Member="CleaningHistoryViews">
    <Type Name="CleaningHistoryView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCleaning" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Employee" Type="System.String" DbType="NVarChar(66)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CleaningScheduleView" Member="CleaningScheduleViews">
    <Type Name="CleaningScheduleView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayOfWeek" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Employee" Type="System.String" DbType="NVarChar(66)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClientsView" Member="ClientsViews">
    <Type Name="ClientsView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Passport" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DaysOfWeekView" Member="DaysOfWeekViews">
    <Type Name="DaysOfWeekView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeesView" Member="EmployeesViews">
    <Type Name="EmployeesView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="WorkState" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FloorsView" Member="FloorsViews">
    <Type Name="FloorsView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryRegistrationHotelView" Member="HistoryRegistrationHotelViews">
    <Type Name="HistoryRegistrationHotelView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Client" Type="System.String" DbType="NVarChar(66)" CanBeNull="true" />
      <Column Name="Passport" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="FloorNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HotelRoomsView" Member="HotelRoomsViews">
    <Type Name="HotelRoomsView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeRoom" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CountRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FloorNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PersonsView" Member="PersonsViews">
    <Type Name="PersonsView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TypesHotelRoomView" Member="TypesHotelRoomViews">
    <Type Name="TypesHotelRoomView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CountRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>